// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcdb

import (
	"encoding/json"
	"time"
)

type Order struct {
	ID        string
	AmountJpy int64
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Payment struct {
	ID           string
	OrderID      string
	Method       string
	Provider     string
	ProviderTxID string
	CreatedAt    time.Time
}

type PaymentEvent struct {
	ID        string
	OrderID   string
	Type      string
	Payload   json.RawMessage
	CreatedAt time.Time
}
